name: Atualizar Data de Conclusão no Projeto

on:
  issues:
    types: [closed]

permissions:
  issues: write
  projects: write

jobs:
  set-completion-date:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar campo de data no Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectFieldName = "Data de Conclusão";
            const issue = context.payload.issue;

            // Obter todos os projetos vinculados à issue
            const projectItems = await github.graphql(`
              query($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          title
                        }
                        fieldValues(first: 20) {
                          nodes {
                            ... on ProjectV2ItemFieldDateValue {
                              field {
                                name
                                id
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { issueId: issue.node_id });

            for (const item of projectItems.node.projectItems.nodes) {
              for (const fieldValue of item.fieldValues.nodes) {
                if (fieldValue.field?.name === projectFieldName) {
                  // Atualiza o campo de data com a data de fechamento
                  await github.graphql(`
                    mutation($itemId: ID!, $fieldId: ID!, $date: Date!) {
                      updateProjectV2ItemFieldValue(input: {
                        projectId: $itemId
                        itemId: $itemId
                        fieldId: $fieldId
                        value: { date: $date }
                      }) {
                        projectV2Item {
                          id
                        }
                      }
                    }
                  `, {
                    itemId: item.id,
                    fieldId: fieldValue.field.id,
                    date: issue.closed_at.split("T")[0]
                  });
                }
              }
            }
