name: Atualizar Data de Conclusão no Project

on:
  issues:
    types: [closed]
  workflow_dispatch:

permissions:
  issues: write

jobs:
  update-project-date:
    runs-on: ubuntu-latest
    steps:
      - name: Atualiza campo de data no Project (Beta)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 1; // Altere para o número do seu projeto se não for 1
            const fieldName = "Data de Conclusão";
            const closedDate = context.payload.issue.closed_at ? context.payload.issue.closed_at.split("T")[0] : new Date().toISOString().split("T")[0];

            // 1. Buscar projetos do repo
            const { repository } = await github.graphql(`
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      number
                      title
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const project = repository.projectsV2.nodes.find(p => p.number === projectNumber);
            console.log("Project encontrado:", project);

            if (!project) {
              core.setFailed('Project não encontrado.');
              return;
            }

            // 2. Buscar items da issue
            const { node } = await github.graphql(`
              query($nodeId: ID!) {
                node(id: $nodeId) {
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          id
                        }
                      }
                    }
                  }
                }
              }
            `, { nodeId: context.payload.issue.node_id });

            console.log("Itens no projeto para essa issue:", node.projectItems.nodes);

            const item = node.projectItems.nodes.find(i => i.project.id === project.id);
            console.log("Item encontrado:", item);

            if (!item) {
              core.setFailed('Item não encontrado no Projeto. A issue precisa ser adicionada manualmente ao Project.');
              return;
            }

            // 3. Buscar campos do projeto
            const { node: projectNode } = await github.graphql(`
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    fields(first: 20) {
                      nodes {
                        id
                        name
                        dataType
                      }
                    }
                  }
                }
              }
            `, { projectId: project.id });

            console.log("Campos disponíveis:", projectNode.fields.nodes);

            const field = projectNode.fields.nodes.find(f => f.name === fieldName);
            console.log("Campo encontrado:", field);

            if (!field) {
              core.setFailed('Campo de data não encontrado.');
              return;
            }

            // 4. Atualizar campo
            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Date!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId,
                    itemId: $itemId,
                    fieldId: $fieldId,
                    value: { date: $value }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId: project.id,
              itemId: item.id,
              fieldId: field.id,
              value: closedDate,
            });
            console.log(`Campo "Data de Conclusão" atualizado para ${closedDate}!`);
