name: Atualizar campo "Data de Fechamento" no Project

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  update-close-date:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar campo de data de fechamento no Project
        uses: actions/github-script@v7
        with:
          script: |
            const projectNumber = 2; // Troque pelo número do seu Project
            const fieldName = "Data de Conclusão"; // Troque pelo nome exato do campo

            // 1. Buscar projetos do repositório
            const projects = await github.graphql(`
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      number
                      title
                      fields(first: 50) {
                        nodes {
                          ... on ProjectV2FieldCommon {
                            id
                            name
                            dataType
                          }
                          ... on ProjectV2DateField {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const project = projects.repository.projectsV2.nodes.find(p => p.number === projectNumber);
            if (!project) {
              core.setFailed('Projeto não encontrado.');
              return;
            }

            // Procura o campo do tipo data pelo nome
            const field = project.fields.nodes.find(f => f.name === fieldName);
            if (!field) {
              core.setFailed('Campo não encontrado.');
              return;
            }

            // 2. Buscar o item da issue no Project
            const items = await github.graphql(`
              query($projectId: ID!, $issueId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            id
                            number
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              projectId: project.id,
              issueId: context.payload.issue.node_id,
            });

            const item = items.node.items.nodes.find(i => i.content && i.content.id === context.payload.issue.node_id);
            if (!item) {
              core.setFailed('Item não encontrado no projeto.');
              return;
            }

            // 3. Atualizar o campo do tipo data
            const closeDate = new Date().toISOString().split('T')[0];
            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: Date!) {
                updateProjectV2ItemFieldValue(
                  input: {
                    projectId: $projectId,
                    itemId: $itemId,
                    fieldId: $fieldId,
                    value: { date: $value }
                  }
                ) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId: project.id,
              itemId: item.id,
              fieldId: field.id,
              value: closeDate,
            });
            console.log(`Campo "${fieldName}" atualizado com a data de fechamento: ${closeDate}`);
