name: Atualizar campo "Data de Fechamento" no Project

on:
  issues:
    types: [closed]

permissions:
  issues: write

jobs:
  update-close-date:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar campo de data de fechamento no Project
        uses: actions/github-script@v7
        with:
          script: |
            const projectNumber = 1; // Troque pelo número do seu Project
            const fieldName = "Data de Fechamento"; // Troque pelo nome exato do campo

            // 1. Buscar projetos do repositório
            const projects = await github.graphql(`
              query($owner: String!, $repo: String!) {
                repository(owner: $owner, name: $repo) {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      number
                      title
                      fields(first: 50) {
                        nodes {
                          ... on ProjectV2FieldCommon {
                            id
                            name
                            dataType
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const project = projects.repository.projectsV2.nodes.find(p => p.number === projectNumber);
            if (!project) {
              core.setFailed('Projeto não encontrado.');
              return;
            }

            const field = project.fields.nodes.find(f => f.name === fieldName);
            if (!field) {
              core.setFailed('Campo não encontrado.');
              return;
            }

            // 2. Buscar o item da issue no Project
            const items = await github.graphql(`
              query($projectId: ID!, $issueId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                           
